# These are supported funding model platforms

github: # Replace with up to 4 GitHub Sponsors-enabled usernames e.g., [user1, user2]
patreon: Lesandu
open_collective: Lesandu
ko_fi: Lesandu
tidelift: Octave
community_bridge: OCtave
liberapay: Lesandu
issuehunt: Lesandu
otechie: Lesandu
custom:  ['https://www.youtube.com/']
